### ISSUE TITLE
Obtaining top contributing voters/explanation for a prediction

### ISSUE THREAD

**Issue by kanghj** [nilesh2797/zestxml#2]
Thanks for the outstanding work on zero-shot XML!

The paper/supplementary material (https://nilesh2797.github.io/pubs/gupta21_supp.pdf) shows a nice UI that visualizes the top active instance label-feature pairs. It looks amazing and helpful to understand the predictions! 

I would like to obtain the same analysis for my own work. Is the code to generate these visualizations (or to obtain the top voters) available?

**Comment by nilesh2797** [comment]
Hi Kang Hong, thanks for your interest in the paper. The visualization was made by manually organizing the data in powerpoint slides. Although, you may find the `get_text` utility in [data_process.ipynb](https://github.com/nilesh2797/zestxml/blob/main/data-process.ipynb) notebook helpful to visualize top features of a row in a sparse csr matrix.
